name: Azure Static Web Apps - Deploy Static Files

on:
  push:
    branches:
      - main

jobs:
  deploy_static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"      # path to your index.html (repo root)
          api_location: ""       # no API in this repo
          output_location: ""    # no build output, upload files as-is
